
INSERT INTO `DRIVER_DETAILS`(
`DRIVER_DETAILS_ID`,
`DRIVER_FNAME`,
`DRIVER_LNAME`,
`DRIVER_AGE`,
`DRIVER_EMAIL`,
`DRIVER_BLOODGRP`,
`DRIVER_LICENSE_NO`,
`DRIVER_LICENSE_ISSUE_DATE`,
`DRIVER_LICENSE_EXP_DATE`,
`DRIVER_LICENSE_STATUS`,
`DRIVER_LICENSE_TEST_STATUS`,
`DRIVER_LICENSE_TYPE`,
`DRIVER_ADDRESS_LINE1`,
`DRIVER_ADDRESS_LINE2`,
`DRIVER_STATE`,
`DRIVER_COUNTRY`,
`DRIVER_POSTALCODE`,
`DRIVER_DOB`,
`DRIVER_LICENSE_TRILLIUM_NO`,
`DRIVER_HEALTH_CARD_EXP_DATE`)  VALUES 
(1,'Alex','dough',35,'alex@gmail.com','o-positive','A1234-12345-12345','2000-08-05','2020-08-05','ACTIVE','NO-REQUIRED','G2','Maplewood Drive','','ON','CANADA','M1E1W7','1984-05-04','1234567','2020-08-05');


INSERT INTO `DRIVER_DETAILS`(
`DRIVER_DETAILS_ID`,
`DRIVER_FNAME`,
`DRIVER_LNAME`,
`DRIVER_AGE`,
`DRIVER_EMAIL`,
`DRIVER_BLOODGRP`,
`DRIVER_LICENSE_NO`,
`DRIVER_LICENSE_ISSUE_DATE`,
`DRIVER_LICENSE_EXP_DATE`,
`DRIVER_LICENSE_STATUS`,
`DRIVER_LICENSE_TEST_STATUS`,
`DRIVER_LICENSE_TYPE`,
`DRIVER_ADDRESS_LINE1`,
`DRIVER_ADDRESS_LINE2`,
`DRIVER_STATE`,
`DRIVER_COUNTRY`,
`DRIVER_POSTALCODE`,
`DRIVER_DOB`,
`DRIVER_LICENSE_TRILLIUM_NO`,
`DRIVER_HEALTH_CARD_EXP_DATE`)  VALUES 
(2,'John','Smith',42,'john@hotmail.com','o-positive','A7869-78965-78965','2000-08-05','2020-08-05','ACTIVE','NO-REQUIRED','G','Brampton','','ON','CANADA','M1E1W9','1979-05-04','68992390','2019-02-05');


INSERT INTO `DRIVER_REGISTRATION`(
`DRIVER_REG_ID`,
`DRIVER_EMAIL`,
`DRIVER_CONTACT_NO`,
`DRIVER_STATUS`) VALUES 
(1,'alex@gmail.com','555555555','ACTIVE');

INSERT INTO `DRIVER_REGISTRATION`(
`DRIVER_REG_ID`,
`DRIVER_EMAIL`,
`DRIVER_CONTACT_NO`,
`DRIVER_STATUS`) VALUES 
(2,'john@hotmail.com','589777555','ACTIVE');